
[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/"
timeout = 100
interval = 10

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci", ]

[build.nixpacksPlan.phases.build]
cmds = ["npm install && npm install dotenv && npm install mysql2 && nix develop -f shell.nix"]

[build.nixpacksPlan.start]
cmd = "npm run dev"
